package com.example.uas_progmob;

import java.util.ArrayList;

public class AwataraData {
    public static String[][] data = new String[][]{
            {"Matsya Awatara", "Ikan Maha Besar", "https://upload.wikimedia.org/wikipedia/id/8/82/Matsya.jpg","Matsya (Dewanagari: मत्‍स्‍य; IAST: matsya) adalah awatara Wisnu yang berwujud ikan raksasa. Dalam bahasa Sanskerta, kata matsya sendiri berarti ikan. Menurut mitologi Hindu, Matsya muncul pada masa Satyayuga, pada masa pemerintahan Raja Satyabrata (lebih dikenal sebagai Maharaja Waiwaswata Manu), putra Wiwaswan, dewa matahari. Matsya turun ke dunia untuk memberitahu Maharaja Manu mengenai bencana air bah yang akan melanda bumi. Ia memerintahkan Maharaja Manu untuk segera membuat bahtera besar."},
            {"Kurma Awatara", "Sang Kura-kura", "https://upload.wikimedia.org/wikipedia/id/1/18/Kurma_awatara.jpg","Kurma (Sanskerta: कुर्म; Kurma) adalah awatara (penjelmaan) kedua dewa Wisnu yang berwujud kura-kura raksasa. Awatara ini muncul pada masa Satyayuga. Menurut kitab Adiparwa, kura-kura tersebut bernama Akupa. Menurut berbagai kitab Purana, Wisnu mengambil wujud seekor kura-kura (kurma) dan mengapung di lautan susu (Kserasagara atau Kserarnawa). Di dasar laut tersebut konon terdapat harta karun dan tirta amerta yang dapat membuat peminumnya hidup abadi. Para Dewa dan Asura berlomba-lomba mendapatkannya. Untuk mengaduk laut tersebut, mereka membutuhkan alat dan sebuah gunung yang bernama Mandara digunakan untuk mengaduknya. Para Dewa dan para Asura mengikat gunung tersebut dengan naga Wasuki dan memutar gunung tersebut. Kurma menopang dasar gunung tersebut dengan tempurungnya. Dewa Indra memegang puncak gunung tersebut agar tidak terangkat ke atas. Setelah sekian lama tirta amerta berhasil didapat dan Dewa Wisnu mengambil alih."},
            {"Waraha Awatara", "Sang Babi Hutan", "https://upload.wikimedia.org/wikipedia/id/f/fc/Varaha.jpg","Waraha (Sanskerta: वाराह; Varāha) adalah awatara (penjelmaan) ketiga dari Dewa Wisnu yang berwujud babi hutan. Awatara ini muncul pada masa Satyayuga (zaman kebenaran). Kisah mengenai Waraha Awatara selengkapnya terdapat di dalam kitab Warahapurana dan Purana-Purana lainnya. Menurut mitologi Hindu, pada zaman Satyayuga (zaman kebenaran), ada seorang raksasa bernama Hiranyaksa, adik raksasa Hiranyakasipu. Keduanya merupakan kaum Detya (raksasa). Hiranyaksa hendak menenggelamkan Pertiwi (planet bumi) ke dalam lautan kosmik, suatu tempat antah berantah di ruang angkasa. Melihat dunia akan mengalami kiamat, Wisnu menjelma menjadi babi hutan yang memiliki dua taring panjang mencuat dengan tujuan menopang bumi yang dijatuhkan oleh Hiranyaksa. Usaha penyelamatan yang dilakukan Waraha tidak berlangsung lancar karena dihadang oleh Hiranyaksa. Maka terjadilah pertempuran sengit antara raksasa Hiranyaksa melawan Dewa Wisnu. Konon pertarungan ini terjadi ribuan tahun yang lalu dan memakan waktu ribuan tahun pula. Pada akhirnya, Dewa Wisnu yang menang. Setelah Dia memenangkan pertarungan, Dia mengangkat bumi yang bulat seperti bola dengan dua taringnya yang panjang mencuat, dari lautan kosmik, dan meletakkan kembali bumi pada orbitnya. Setelah itu, Dewa Wisnu menikahi Dewi Pertiwi dalam wujud awatara tersebut."},
            {"Narasimha Awatara", "Manusia Berkepala Singa", "https://upload.wikimedia.org/wikipedia/id/8/8d/Nrsimhadev.jpg","Narasinga (Devanagari: नरसिंह ; disebut juga Narasingh, Nārasiṃha) adalah awatara (inkarnasi/penjelmaan) Wisnu yang turun ke dunia, berwujud manusia dengan kepala singa, berkuku tajam seperti pedang, dan memiliki banyak tangan yang memegang senjata. Narasinga merupakan simbol dewa pelindung yang melindungi setiap pemuja Wisnu jika terancam bahaya."},
            {"Wamana Awatara", "Sang Orang Cebol", "https://upload.wikimedia.org/wikipedia/id/c/c4/Vamanadeva.jpg","Wamana (Devanagari: वामन ; Vāmana) adalah awatara Wisnu yang kelima, turun pada masa Tretayuga, sebagai putra Aditi dan Kasyapa, seorang Brahmana. Ia (Wisnu) turun ke dunia guna menegakkan kebenaran dan memberi pelajaran kepada raja Bali (Mahabali), seorang Asura, cucu dari Prahlada. Raja Bali telah merebut surga dari kekuasaan Dewa Indra, karena itu Wisnu turun tangan dan menjelma ke dunia, memberi hukuman pada Raja Bali. Wamana awatara dilukiskan sebagai Brahmana dengan raga anak kecil yang membawa payung. Wamana Awatara merupakan penjelmaan pertama Dewa Wisnu yang mengambil bentuk manusia lengkap, meskipun berwujud Brahmana mungil. Wamana kadang-kadang dikenal juga dengan sebutan Upendra."},
            {"Parasurama Awatara", "Sang Rama Bersenjata Kapak", "https://upload.wikimedia.org/wikipedia/commons/f/fd/Parashurama_with_axe.jpg","Parasurama (Dewanagari: परशुरामभार्गव; IAST: Parashurāma Bhārgava) atau yang di Indonesia kadang disebut Ramaparasu, adalah nama seorang tokoh Ciranjiwin (abadi) dalam ajaran agama Hindu. Secara harfiah, nama Parashurama bermakna Rama yang bersenjata kapak. Nama lainnya adalah Bhargawa yang bermakna keturunan Maharesi Bregu. Ia sendiri dikenal sebagai awatara Wisnu yang keenam dan hidup pada zaman Tretayuga. Pada zaman ini banyak kaum kesatria yang berperang satu sama lain sehingga menyebabkan kekacauan di dunia. Maka, Wisnu sebagai dewa pemelihara alam semesta lahir ke dunia sebagai seorang brahmana berwujud angker, yaitu Rama putra Jamadagni, untuk menumpas para kesatria tersebut."},
            {"Rama Awatara", "Sang Ksatria", "https://upload.wikimedia.org/wikipedia/id/4/4d/Rama_purusothama.jpg","Rama (Sanskerta: राम; Rāma) atau Ramacandra (Sanskerta: रामचन्द्र; Rāmacandra) adalah seorang raja legendaris yang terkenal dari India yang konon hidup pada zaman Tretayuga, keturunan Dinasti Surya atau Suryawangsa. Ia berasal dari Kerajaan Kosala yang beribukota Ayodhya. Menurut pandangan Hindu, ia merupakan awatara Dewa Wisnu yang ketujuh yang turun ke bumi pada zaman Tretayuga. Sosok dan kisah kepahlawanannya yang terkenal dituturkan dalam sebuah sastra Hindu Kuno yang disebut Ramayana, tersebar dari Asia Selatan sampai Asia Tenggara. Terlahir sebagai putera sulung dari pasangan Raja Dasarata dengan Kosalya, ia dipandang sebagai Maryada Purushottama, yang artinya Manusia Sempurna. Setelah dewasa, Rama memenangkan sayembara dan beristerikan Dewi Sita, inkarnasi dari Dewi Laksmi. Rama memiliki anak kembar, yaitu Kusa dan Lawa."},
            {"Kresna Awatara", "Putra Wasudewa", "https://upload.wikimedia.org/wikipedia/id/a/a3/Krsna_flute_big.jpg","Kresna atau Krisna (Dewanagari: कृष्ण; IAST: kṛṣṇa; dibaca [ˈkr̩ʂɳə]) adalah salah satu dewa yang dipuja oleh umat Hindu, berwujud pria berkulit gelap atau biru tua, memakai dhoti kuning dan mahkota yang dihiasi bulu merak. Dalam seni lukis dan arca, umumnya ia digambarkan sedang bermain seruling sambil berdiri dengan kaki yang ditekuk ke samping. Legenda Hindu dalam kitab Purana dan Mahabharata menyatakan bahwa ia adalah putra kedelapan Basudewa dan Dewaki, bangsawan dari kerajaan Surasena, kerajaan mitologis di India Utara. Secara umum, ia dipuja sebagai awatara (inkarnasi) Dewa Wisnu kedelapan di antara sepuluh awatara Wisnu. Dalam beberapa tradisi perguruan Hindu, misalnya Gaudiya Waisnawa, ia dianggap sebagai manifestasi dari kebenaran mutlak, atau perwujudan Tuhan itu sendiri,[1] dan dalam tafsiran kitab-kitab yang mengatasnamakan Wisnu atau Kresna, misalnya Bhagawatapurana, ia dimuliakan sebagai Kepribadian Tuhan Yang Maha Esa."},
            {"Buddha Awatara", "Pangeran Siddharta Gautama", "https://upload.wikimedia.org/wikipedia/commons/8/8d/Buddha_meditating.jpg","Buddha Gautama muncul dalam kitab Purana (Susastra Hindu) sebagai awatara (inkarnasi) kesembilan di antara sepuluh awatara (Dasawatara) Dewa Wisnu. Dalam Bhagawatapurana, Dia disebut sebagai awatara kedua puluh empat di antara dua puluh lima awatara Wisnu. Kata buddha berarti Dia yang mendapat pencerahan dan dapat mengacu kepada Buddha lainnya selain Buddha Gautama, pendiri Buddhisme yang dikenal pada masa sekarang. Berbeda dengan ajaran Hindu, ajaran Buddha Gautama tidak menekankan keberadaan Tuhan sang Pencipta sehingga agama Buddha termasuk bagian dari salah satu aliran nāstika (heterodoks; secara harfiah berarti Itu tidak ada) menurut aliran-aliran agama Dharma lainnya, seperti Dwaita. Namun beberapa aliran lainnya, seperti Adwaita, sangat mirip dengan ajaran Buddhisme, baik bentuk maupun filsafatnya."},
            {"Kalki Awatara", "Sang Pemusnah", "https://upload.wikimedia.org/wikipedia/id/7/76/KalkiAvatara.jpg"," Kalki (Dewanagari: कल्कि; IAST: Kalki; juga ditulis sebagai Kalkin dan Kalaki) adalah awatara Wisnu kesepuluh, sekaligus yang terakhir, yang akan datang pada akhir zaman Kaliyuga (zaman kegelapan dan kehancuran). Berbagai tradisi Hindu memiliki berbagai kepercayaan dan pemikiran mengenai kapan, bagaimana, di mana, dan mengapa Kalki muncul. Secara umum, Kalki dikatakan sebagai awatara yang mengendarai kuda putih (beberapa sumber mengatakan nama kudanya Devadatta [anugerah Dewa] dan dilukiskan sebagai kuda bersayap). Kalki memiliki pedang berkilat yang digunakan untuk memusnahkan kejahatan dan menghancurkan iblis Kali, kemudian menegakkan kembali darma dan memulai zaman yang baru."}
    };

    public static ArrayList<Awatara> getListData(){
        Awatara awatara = null;
        ArrayList<Awatara> list = new ArrayList<>();
        for (String[] aData : data) {
            awatara = new Awatara();
            awatara.setName(aData[0]);
            awatara.setRemarks(aData[1]);
            awatara.setPhoto(aData[2]);
            awatara.setDescription(aData[3]);

            list.add(awatara);
        }

        return list;
    }
}
